### PR TITLE
amd64 can walk past the end of the aux vector and SIGSEGV

### PR DESCRIPTION
**Pull request by bgaff**
As currently written the amd64 stub will happily walk past the end of the aux vector, it never checks for AT_NULL. This can be problematic when certain fields are not present, such as AT_BASE. However, in the case of non-interpreted binaries the absence of AT_BASE is actually fine.

### CODE REVIEW

**Comment by markus-oberhumer** [comment]
John, please have a look. CI failures are because of testsuite checksum changes.

**Comment by jreiser** [comment]
Yes, bgaff found a bug and its fix.  I made the corresponding changes to the other *.elf-main.c, then built new stubs, and updated the testsuite results.

**Review by jreiser — COMMENTED** [review]
Several other *.elf-main.c needed the same fix.  Integrated onto <tt>devel</tt>, re-built stubs, re-made testsuite, pushed (see "git log")

**Comment by markus-oberhumer** [comment]
This is now fixed, thanks!

**Pull request closed without merging**
