### PR TITLE
fix kerning on ascii art logo

### PR DESCRIPTION
**Pull request by J-Zeitler**

### CODE REVIEW

**Review by mathieu-aubin — APPROVED** [review]
altho not a must, it makes a difference to me

**Comment by markus-oberhumer** [comment]
Hi, thanks for that update - I'll have a look.

FYI, the logo was created back in 1998 with [FIGlet](https://en.wikipedia.org/wiki/FIGlet) - but maybe there are some better tools these days?

**Comment by J-Zeitler** [comment]
Hi,

I didn't use any generator for this, just manually added some kerning I thought looked good.

This pull request wasn't meant to take up peoples valuable time though since it does not add any functionality to the project. Feel free to what you like with it.

**Comment by mathieu-aubin** [comment]
merge

**Comment by markus-oberhumer** [comment]
Fixed in https://github.com/upx/upx/commit/8cad78f3b46ab74f53a1112124dcde14c6f2daa8 .

**Pull request closed without merging**
