### PR TITLE
Create Fuzzer using libfuzzer

### PR DESCRIPTION
**Pull request by liamjm**
First step to integrate with OSS Fuzz (https://github.com/upx/upx/issues/244), is to create the fuzzer.

In line with the discussions in this repo, the focus is on the decompression / unpacking operation, as this is when the user could be handling untrusted input.

There are 2 changes to the existing code base:
* disable the exit() on error, to allow the fuzzer to keep running.
* separate out the guts of main() into real_main() and move main() to its own file to allow the fuzzer to provide its own main().
I'm happy to discuss other solutions to the above problems!

### CODE REVIEW

**Comment by liamjm** [comment]
@jreiser

**Comment by liamjm** [comment]
It is not clear to me why there are errors from the CI pipeline as this code hasn't been touched:

```
c:\projects\upx\src\pefile.cpp(2251) : error C2220: warning treated as error - no 'object' file generated
        c:\projects\upx\src\pefile.cpp(3114) : see reference to function template instantiation 'void PeFile::pack0<LE32,PeFile32::pe_header_t>(OutputFile *,ht &,ht &,unsigned int,upx_uint64_t,bool)' being compiled
        with
        [
            ht=PeFile32::pe_header_t
        ]
c:\projects\upx\src\pefile.cpp(2251) : warning C4245: 'argument' : conversion from 'int' to 'unsigned int', signed/unsigned mismatch
c:\projects\upx\src\pefile.cpp(2251) : warning C4245: 'argument' : conversion from 'int' to 'unsigned int', signed/unsigned mismatch
        c:\projects\upx\src\pefile.cpp(3169) : see reference to function template instantiation 'void PeFile::pack0<LE64,PeFile64::pe_header_t>(OutputFile *,ht &,ht &,unsigned int,upx_uint64_t,bool)' being compiled
        with
        [
            ht=PeFile64::pe_header_t
        ]
```

**Comment by liamjm** [comment]
CI pipeline has been broken for a while: 
https://ci.appveyor.com/project/markus-oberhumer/upx/history

**Comment by markus-oberhumer** [comment]
We're currently working on the UPX 4 release, so I would prefer if you'd maintain these fuzzing patches in your own tree for the time being. Thanks!

**Comment by liamjm** [comment]
What is the time frame for the v4 release?

For my education, what is the concern with this patch? Is it time to review, that is makes changes to main.cpp, a new directory etc?

I was hoping to have this fuzzing code in the main repo, not my fork for several reasons:
* #244 talks of integrating UPX with OSS-fuzz. I'm not sure if using my fork would be acceptable and it certainly is not ideal.
* #427 talks of creating a sandbox for UPX. This would also like to make use of the changes in this PR to main.cpp. Without this PR, landing this feature would be blocked. Would you be willing to accept PRs for this feature at this time anyway?

**Comment by markus-oberhumer** [comment]
Ok, since 36f2ff2fa0c2483f7fd86deb16f20cb33eb4af92 you should now be able to call `upx_main`, and building with -DWITH_GUI also disables the real `main`.

**Comment by jreiser** [comment]
@markus-oberhumer  That version fails to compile for me:
```
$ git checkout devel
Already on 'devel'
Your branch is up to date with 'origin/devel'.
$ git diff  # output is empty
$ git log -n 1
commit 36f2ff2fa0c2483f7fd86deb16f20cb33eb4af92 (HEAD -> devel, origin/devel)
Author: Markus F.X.J. Oberhumer <markus@oberhumer.com>
Date:   Mon Dec 14 22:10:07 2020 +0100

    Extract upx_main() for compilation with -DWITH_GUI.
$ set | grep UPX
UPX_LUADIR=/path/to/lua-5.1.1
UPX_UCLDIR=/path/to/ucl-1.03
$ make clean
rm -f *.d *.ii *.map *.o *.obj *.res ./.depend upx.exe upx.out upx.ttp upx.out
$ make
Updating .depend
/bin/sh: -DUPX_VERSION_GITREV="36f2ff2fa0c2+": command not found
make: *** Deleting file '.depend'
make: *** No rule to make target '.depend', needed by 'c_file.o'.  Stop.
$ make --version
GNU Make 4.2.1
Built for x86_64-redhat-linux-gnu
Copyright (C) 1988-2016 Free Software Foundation, Inc.
```

**Comment by markus-oberhumer** [comment]
Yes, my bad, as I always set CXX to some value. Should be fixed in devel now.

**Pull request closed without merging**
