### PR TITLE
src: add support for loongarch

### PR DESCRIPTION
**Pull request by wuruilong01**

### CODE REVIEW

**Comment by markus-oberhumer** [comment]
Thanks for that, but why is this needed? UPX should compile on loongarch just nicely.

**Comment by wuruilong01** [comment]
I encountered an issue while compiling in Debian, but after making changes following the instructions in the PR, it now compiles successfully. For more details about the issue, please see the link.
[https://buildd.debian.org/status/fetch.php?pkg=upx-ucl&arch=loong64&ver=3.96-3&stamp=1693586995&raw=0](url)

**Comment by markus-oberhumer** [comment]
Ok, I see. Debian should upgrade to 4.1.0.

EDIT: there have been important fixes and adaptions for current kernels/binutils in recent UPX versions, so they really should upgrade!

**Comment by markus-oberhumer** [comment]
I'm closing this as it is not needed for current UPX versions. Please try to convince the Debian maintainers to upgrade.

**Comment by wuruilong01** [comment]
Thanks

**Comment by markus-oberhumer** [comment]
Related link: https://bugs.debian.org/cgi-bin/pkgreport.cgi?pkg=upx-ucl;dist=unstable

**Comment by yzewei** [comment]
＠wuruilong01 After you add this patch, can UPX compress the binary under Loongarch64, it seems to be a failure

**Comment by wuruilong01** [comment]
> Thanks for that, but why is this needed? UPX should compile on loongarch just nicely.

@yzewei 根据维护者的回复， 最新版本可以在loongarch架构上正常运行。

- 为什么要使用这个PR？
- 详细的错误是什么呢？

**Comment by yzewei** [comment]
> > Thanks for that, but why is this needed? UPX should compile on loongarch just nicely.
> 
> @yzewei 根据维护者的回复， 最新版本可以在loongarch架构上正常运行。
> 
> * 为什么要使用这个PR？
> * 详细的错误是什么呢？

@wuruilong01 在新世界使用时出现无法识别loongarch下二进制文件的问题。
* 使用loongarch版本的upx进行二进制压缩
* 具体错误如下：
   `[root@bogon /]$ upx kafka_exporter
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2023
UPX git-877911+ Markus Oberhumer, Laszlo Molnar & John Reiser    Aug 8th 2023

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: kafka_exporter: UnknownExecutableFormatException

Packed 0 files.

WARNING: this is an unstable beta version - use for testing only! Really.
系统版本如下:
`
[root@bogon /]$ cat /etc/os-release 
NAME="Anolis OS"
VERSION="23"
ID="anolis"
VERSION_ID="23"
PLATFORM_ID="platform:an23"
PRETTY_NAME="Anolis OS 23"
ANSI_COLOR="0;31"
HOME_URL="https://openanolis.cn/"
BUG_REPORT_URL="https://bugzilla.openanolis.cn/"
`

`

**Comment by markus-oberhumer** [comment]
This issue is about compiling UPX on a loongarch **host** system.

Target support for loongarch is not (yet) implemented.

**Comment by yzewei** [comment]
@markus-oberhumer  thanks! But I want to know whether UPX is about planning to support the Loongarch, and can it point out the key steps to support Loongarch? Thanks again!

**Pull request closed without merging**
